name: Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Update latest.json
      uses: docker://docker.io/python:alpine
      with:
        args: python3 progress/process.py progress/data public
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
